// <auto-generated />
namespace ProjectITP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _29th1stcorrectionisdone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_29th1stcorrectionisdone));
        
        string IMigrationMetadata.Id
        {
            get { return "201908291526029_29th 1st correction is done"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
